### ISSUE TITLE
Practica 1 Mockup 

### ISSUE THREAD

**Issue by KevCH24** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-4as_coders#2]
ARCHIVO PDF:

[Practica 1 Mockup - Trabajo en equipo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-4as_coders/files/14283764/Practica.1.Mockup.-.Trabajo.en.equipo.pdf)

ENLACE DE FIGMA: 

https://www.figma.com/file/Zl3kqPjNrm6qFZfcF3qJbW/Untitled?type=design&node-id=204-16&mode=design&t=SKURqA85q4ofOwPp-0

**Comment by 22620229Angel** [comment]
Nuestro equipo le da una calificación de 95 a nuestro parecer está muy bien estructurado y contiene los puntos y la información necesaria.
El único detalle es que le faltó la tabla de ilustraciones.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
